CREATE TABLE [dbo].[CustomerDetail]
(
	[CustomerNo] INT PRIMARY KEY NOT NULL IDENTITY,
[Name] NVARCHAR (50) NOT NULL,
[StreetAddress] NVARCHAR (50) NOT NULL,
[City] NVARCHAR (50) NOT NULL,
[State] NVARCHAR (50) NOT NULL
)
